version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1505_800Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_1505_800.integrations:test
  packages:
  - name: Kvv_1505_800Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
